### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by ffranr**

### CODE REVIEW

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Comment by ffranr** [comment]
I don't think I have the correct rights to request a re-run of the CI. @Roasbeef @guggero could you guys press re-run please? It would be interesting to see whether we see the same error.

**Comment by guggero** [comment]
Re-ran CI, seems to be a flake. Created [an issue](https://github.com/lightninglabs/taro/issues/192) to track the flake.

**Review by Roasbeef — APPROVED** [review]
LGTM 🦨

**Pull request merged**
