### PR TITLE
build: update to sqlc v1.16.0

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we update to sqlc v1.16.0. Relevant release notes here: https://github.com/kyleconroy/sqlc/releases/tag/v1.16.0.

### CODE REVIEW

**Review by guggero — CHANGES_REQUESTED** [review]
Looks like we should also run `make sqlc` to commit the diff (just the version number in the generated files). The CI didn't detect it because we run `make sqlc` instead of `make sqlc-check` in the `sqlc-check` step of the GitHub Actions workflow.

**Comment by Roasbeef** [comment]
> Looks like we should also run make sqlc to commit the diff (just the version number in the generated files

You mean it should ensure that there's no generated diff? Just pushed an extra commit to compile w/ the new version.

**Comment by guggero** [comment]
> You mean it should ensure that there's no generated diff?

I mean the CI didn't detect it because we call the wrong command in the GitHub Actions YAML. I think we should fix that as well since it's a one line change.

**Comment by Roasbeef** [comment]
Looks like we're hitting that same linter issue here: 
```
cmd/tarod/main.go:1: : error obtaining VCS status: exit status 128
```

**Review by guggero — APPROVED** [review]

**Comment by guggero** [comment]
Needs a rebase after the CI/linter fix.

**Pull request merged**
